### PR TITLE
add Go dependencies by godep

### PR DESCRIPTION
**Pull request by paulz**
Thank you for the awesome CLI interface for Google Drive!

In addition to managing dependencies this will allow building `Homebrew` formula  easier, so we can install `gdrive` using:

`brew install gdrive`

see https://github.com/tools/godep

### CODE REVIEW

**Comment by paulz** [comment]
We would like to be able to install `gdrive` on mac using `Homebrew` official formula.

Currently we have to use a workaround by doing:
`brew tap paulz/gdrive`
`brew install --HEAD drive`

because old formula was not building correctly and was moved to https://github.com/Homebrew/homebrew-boneyard/blob/master/gdrive.rb

New formula could be written much simpler given dependencies:
https://github.com/paulz/homebrew-gdrive/blob/master/gdrive.rb

**Comment by prasmussen** [comment]
Thanks, I wanted to use the new vendoring feature of 1.5+, but never got around to doing it.

**Comment by paulz** [comment]
Thank you, @prasmussen!

Would you be able cut a new release of the `Google Drive CLI Client`? This will allow us to use release tag in [Homebrew](http://brew.sh) formula. And promoting formula to the main repo will allow anyone with **Homebrew** to use it. Here is the plan to restore **Homebrew** installation for **GDrive**:
[https://github.com/paulz/homebrew-gdrive#todo](https://github.com/paulz/homebrew-gdrive#todo)

**Comment by prasmussen** [comment]
I've tagged the latest commit as 2.1.0

**Comment by paulz** [comment]
Thank you! The Homebrew core team accepted our formula for gdrive:
https://github.com/Homebrew/homebrew-core/pull/754

Now anyone can install **gdrive** on Mac:
```
brew install gdrive
```
I can offer to maintain and update the formula with your new releases:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/gdrive.rb

Thank you @prasmussen for the awesome **gdrive** utility!

**Comment by prasmussen** [comment]
Cool, great work :)

**Pull request merged**
